name: CI

on: [push]
        
jobs:
    build:
  
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 11.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 11.14.0
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist/ubb
          BUILD_SCRIPT: yarn install && yarn run build -- --prod
